//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_Vuelos_Main_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public decimal id { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public string registro_detalle { get; set; }
        public string usuario { get; set; }
        public decimal operacion { get; set; }
        public string descripcion { get; set; }
    }
}
