//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_Vuelos_Main_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteWeb
    {
        public string usuario { get; set; }
        public string nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public string correo { get; set; }
        public string contrasena { get; set; }
        public decimal pregunta_seguridad { get; set; }
        public string respuesta_seguridad { get; set; }
    }
}
