//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_Vuelos_Main_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class V_Vuelos_MainEntities : DbContext
    {
        public V_Vuelos_MainEntities()
            : base("name=V_Vuelos_MainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aerolinea> Aerolinea { get; set; }
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<Boleto> Boleto { get; set; }
        public virtual DbSet<ClienteToken> ClienteToken { get; set; }
        public virtual DbSet<ClienteWeb> ClienteWeb { get; set; }
        public virtual DbSet<Consecutivo> Consecutivo { get; set; }
        public virtual DbSet<Error> Error { get; set; }
        public virtual DbSet<EstadoPuerta> EstadoPuerta { get; set; }
        public virtual DbSet<EstadoVuelo> EstadoVuelo { get; set; }
        public virtual DbSet<FormaPago> FormaPago { get; set; }
        public virtual DbSet<Operacion> Operacion { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Pregunta> Pregunta { get; set; }
        public virtual DbSet<Puerta> Puerta { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Tarjeta> Tarjeta { get; set; }
        public virtual DbSet<TipoTarjeta> TipoTarjeta { get; set; }
        public virtual DbSet<TipoTransaccion> TipoTransaccion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Vuelo> Vuelo { get; set; }
    
        public virtual int uspCambiarContrasenaUsuario(string nombreUsuario, string nuevaContrasena)
        {
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("nombreUsuario", nombreUsuario) :
                new ObjectParameter("nombreUsuario", typeof(string));
    
            var nuevaContrasenaParameter = nuevaContrasena != null ?
                new ObjectParameter("nuevaContrasena", nuevaContrasena) :
                new ObjectParameter("nuevaContrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspCambiarContrasenaUsuario", nombreUsuarioParameter, nuevaContrasenaParameter);
        }
    
        public virtual ObjectResult<uspRecuperarAerolineaPorPais_Result> uspRecuperarAerolineaPorPais(string idPais)
        {
            var idPaisParameter = idPais != null ?
                new ObjectParameter("idPais", idPais) :
                new ObjectParameter("idPais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspRecuperarAerolineaPorPais_Result>("uspRecuperarAerolineaPorPais", idPaisParameter);
        }
    
        public virtual ObjectResult<uspRecuperarPuertasActivas_Result> uspRecuperarPuertasActivas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspRecuperarPuertasActivas_Result>("uspRecuperarPuertasActivas");
        }
    
        public virtual ObjectResult<uspRecuperarVuelos_Result> uspRecuperarVuelos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspRecuperarVuelos_Result>("uspRecuperarVuelos");
        }
    }
}
