//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_Vuelos_Main_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public string numero_tarjeta { get; set; }
        public string fecha_expiracion { get; set; }
        public Nullable<decimal> tipo_tarjeta { get; set; }
        public string cliente { get; set; }
        public string cvv { get; set; }
    }
}
