//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_Vuelos_Main_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelo
    {
        public string id { get; set; }
        public string fecha_partida { get; set; }
        public string hora_partida { get; set; }
        public string fecha_llegada { get; set; }
        public string hora_llegada { get; set; }
        public string aerolinea { get; set; }
        public string puerta { get; set; }
        public decimal estado { get; set; }
        public string parte_de { get; set; }
        public string llega_a { get; set; }
    }
}
